### PR TITLE
bump version to 1.3.0

### PR DESCRIPTION
**Pull request by hirasso**

### CODE REVIEW

**Comment by hirasso** [comment]
ok, bumped the version number. Now how do I get it to npm? I would need a one-time password as it seems:

```
❯ npm publish
npm notice 
npm notice 📦  @swup/scroll-plugin@1.3.0
npm notice === Tarball Contents === 
npm notice 1.1kB  LICENSE                     
npm notice 35.3kB dist/SwupScrollPlugin.js    
npm notice 16.6kB dist/SwupScrollPlugin.min.js
npm notice 1.1kB  package.json                
npm notice 5.7kB  readme.md                   
npm notice === Tarball Details === 
npm notice name:          @swup/scroll-plugin                     
npm notice version:       1.3.0                                   
npm notice filename:      @swup/scroll-plugin-1.3.0.tgz           
npm notice package size:  14.5 kB                                 
npm notice unpacked size: 59.7 kB                                 
npm notice shasum:        16d4c396917ae4ee95c249fdc9e5bab34740b02d
npm notice integrity:     sha512-7/NZZZmlZpRVN[...]PqfkLXGHd8mpA==
npm notice total files:   5                                       
npm notice 
This operation requires a one-time password.
Enter OTP: 
```

**Comment by hirasso** [comment]
I did the last npm publish 3 years ago and forgot all about it 😅

**Comment by daun** [comment]
Same as with core, tag a release on GitHub after merging the PR. Thr npm publish action is already in place.

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
Hmm, still can't run the action. There is no button for me

**Comment by daun** [comment]
No need to run the action. When you create a release and tag it 1.3.0, it will auto-publish to npm. Have you created a release?

**Comment by hirasso** [comment]
Thanks. God I need to get the hang of this 😄

**Pull request merged**
