### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by hirasso**
Add docs for the new options `scrollContainers` and `shouldRestoreScrollPosition`

### CODE REVIEW

**Comment by daun** [comment]
I think we need some clarity about when/why this is useful. Along the lines of...

The scroll plugin works out of the box for sites where the window is the main scroll container.

If your site has other scroll containers than the window, like overflowing divs, the scroll plugin will happily restore their scroll positions as long as you let it know about those containers. You can either add the attribute `[data-swup-scroll-container]` to them or use a custom selector: (options example)

On each page navigation, the plugin will **reset** the scroll position to the top just like the browser would. On backword/forward history visits, it will **restore** the previous scroll position that was saved right before leaving the page. 

You can customize when to reset vs. restore using the `shouldRestoreScrollPosition` callback. A common use case would be a custom back button: clicking it will reset the scoll position to the top while users will expect it to restore the previous scroll position on that page.

```js
{
    // Don't scroll back up for custom back-links, mimicking the browser back button
    shouldRestoreScrollPosition: (htmlAnchorElement) => {
      return htmlAnchorElement.classList.contains('backlink');
    }
}
```

**Comment by hirasso** [comment]
That's much better than my version! Would you care to implement this?

**Comment by daun** [comment]
Sure 🥒

**Comment by daun** [comment]
@hirasso Does the `shouldRestoreScrollPosition ` callback only work for overflow containers or the window as well? If yes, I'll include that. If no, I'd like to tackle that too before releasing it.

**Comment by hirasso** [comment]
Also works for the window :)

**Comment by hirasso** [comment]
You can test it on my test site

**Comment by daun** [comment]
I've added a few things, looks okay for you?

**Review by daun — DISMISSED** [review]

**Comment by daun** [comment]
Feel free to merge or push more changes.

**Comment by hirasso** [comment]
Looks great! Actually, reading this, I got unsure if the callback `shouldRestoreScrollPositions` shouldn't actually be called `shouldResetScrollPositions` and resolve to `true` by default. I usually find it more intuitive if a function's default behavior is truthy. If you agree, we would have to do another round, but I think it could save us quite some support hassle down the road.

**Comment by daun** [comment]
True, let's rename it. Can you do both the renaming and the adjustments for the docs in this PR? Or does that get messy?

**Comment by hirasso** [comment]
I think this should work.

**Comment by daun** [comment]
I've pushed a minor change.

One question: in `onClickLink`, you changed from

```js
if (!this.options.shouldRestoreScrollPosition(e.delegateTarget))
```

to 

```js
if (!this.options.shouldResetScrollPosition(e.delegateTarget)) {
```

Shouldn't the exclamation mark have changed as well? As we're inverting from `true` to `false` as default behavior?

**Comment by hirasso** [comment]
Yeah, I think we fixed a bug here. Returning if the condition evaluates to false is the correct thing here ... i guess ... 😴🤤

**Comment by daun** [comment]
Nice, I'll merge now, let's make sure and test it tomorrow before cutting a release.

**Review by daun — APPROVED** [review]

**Pull request merged**
