### PR TITLE
Refactor and cleanup

### PR DESCRIPTION
**Pull request by hirasso**
With a fresh mind I did some cleanup and tested it again. Works great for me!

While adding more JSDoc to the code, I noticed this in `unmount()`:
```js
window.history.scrollRestoration = 'auto';
```
This should not be hardcoded, since the scrollRestoration could have been already altered before the plugin was initialized. So I saved the previous value and reset it in `unmount()` like so:

```
window.history.scrollRestoration = this.previousScrollRestoration;
```
I hope it's ok that this became part of this PR.

### CODE REVIEW

**Comment by daun** [comment]
I love the added doc comments, we should look into slowly adding those to the core as well and start generating type definitions.

**Review by daun — APPROVED** [review]

**Comment by hirasso** [comment]
Ready for a new version I would say! 🍾

**Comment by daun** [comment]
Feel free to create a PR for the version bump! We still have to add the version bump action to all the plugins.

**Comment by daun** [comment]
Will this be a breaking change? Since we're restoring a different value for scroll restoration. Or we wait until we figure out scrolling when `animateHistoryBrowsing` is enabled and bump the major version then.

**Comment by hirasso** [comment]
No, this is not introducing breaking changes. The scroll position of the next (link-click) page is always being reset, if not overwritten by `shouldResetScrollPosition`. Let's handle `animateHistoryBrowsing` in the next release.

**Comment by hirasso** [comment]
Sems like I can't run the workflow here?

Screen Shot 2022-08-19 at 13 06 45

**Comment by daun** [comment]
Perfect, let's bump minor now and major if we ever tackle animated history browsing.

**Comment by daun** [comment]
Yeah, the workflow only exists on the core repo for now. You need to create a PR after running npm version.

**Pull request merged**
